### ISSUE TITLE
Player Freeze

### ISSUE THREAD

**Issue by NotKrma** [utkuali/pacificheist-ESX-#9]
When i want to start the heist, the player freeze, no error on console, and F8, the robbery dont start, only i see the first animation and the player freezes

**Comment by utkuali** [comment]
there is error in your console possibly saying no such exports "SendAlert",
so check if you have progressBars, then check if you have mythic_notify, and then check if you have the latest mythic_notify, in client.lua inside mythic_notify there has to be a function named "SendAlert", if you don't have that, simply go to utk_ornateheist/client.lua and change every SendAlert to DoHudText

**Comment by NotKrma** [comment]
Yes, it was the solution. I leave you a coment in the patreon zone.

**Comment by WantToLearnCoding** [comment]
Hi, I just downloaded your script and this issue still existed. I already changed every SendAlert to DoHudText in the client.lua. Since the link you provided for mythic_notify  is no longer available I am thinking that is causing the issue. Although I'm still expecting that by the time I change the SendAlert to DoHudText the issue will be fixed but still it is not. Can you fix it?
